language: node_js
node_js:
  - 0.10
before_script:
  - mkdir jar
  - wget -O jar/tika-app.jar http://psg.mtu.edu/pub/apache/tika/tika-app-1.8.jar
  - sudo apt-get update -qq
  - sudo apt-get install -qq openjdk-7-jdk
  - java -version
  - npm install -g grunt-cli
