language: node_js
node_js:
  - 0.10
before_script:
  - mkdir jar
  - wget http://apache.cs.utah.edu/tika/tika-app-1.6.jar -o jar/tika-app-1.6.jar
  - sudo apt-get install openjdk-7-jdk
  - npm install -g grunt-cli
